# Site settings
title: BDSM in Riga
description: BDSM in Latvia
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Secret BDSM in Riga
user_description: Riga BDSM 
user_title: Contact to find more. anna@femdom.lv
email: anna@femdom.lv

# Google-analytics
google-analytics:
  id: "UA-111457908-2"

exclude: ['package.json', 'src' , 'node_modules']
