# Site settings
title: Riga
description: Latvia
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Coming soon
user_description: Riga
user_title: Contact to find more.
email: domainlv@gmail.com

# Google-analytics
google-analytics:
  id: "UA-111457908-2"

exclude: ['package.json', 'src' , 'node_modules']
