# Site settings
title: Best massage in Riga
description: best massage place in Riga Latvia
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: This Domain 
user_description: This domain name is for sale. 
user_title: IS FOR SALE!
email: domainlv@gmail.com

# Google-analytics
google-analytics:
  id: "UA-111457908-2"

exclude: ['package.json', 'src' , 'node_modules']
